[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"
author = "Konstantin Sivakov <konstantin.sivakov@gmail.com>"
description = "Advent of Code 2024 solutions"


[dependencies]
reqwest = { version = "0.11.6", features = ["blocking"] }
dotenv = "0.15.0"